name: Release
on: [workflow_dispatch]

permissions:
  contents: write

env:
  ENVIRONMENT: production

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          # Modrinth
          modrinth-id: fSQghQl2
          modrinth-featured: true
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # CurseForge
          curseforge-id: 662163
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # Config
          name: Bella v1.1.0 (Quilt 1.19.2)
          version: v1.1.0+1.19.2
          version-type: release
          changelog-file: CHANGELOG.md
          files-primary: build/libs/!(*-@(dev|sources)).jar
          files-secondary: ""

          loaders: |
            quilt
          game-versions: |
            1.19.2
          dependencies: |
            qsl | depends | *
          java: |
            17

          retry-attempts: 2
          retry-delay: 10000

      - name: Publish (GitHub)
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          # GitHub
          github-tag: v1.1.0-1.19.2
          github-draft: false
          github-prerelease: false
          github-commitish: 1.19
          github-token: ${{ secrets.GITHUB_TOKEN }}

          name: Bella v1.1.0 (Quilt 1.19.2)
          version: v1.1.0+1.19
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: |
            quilt
          game-versions: |
            1.19.2
          dependencies: |
            qsl | depends | *
          java: |
            17

          retry-attempts: 2
          retry-delay: 10000
